
import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { BookOpen, Sparkles, Heart, Lightbulb, Calendar, Tag, Trash2, Download, Upload, Feather } from 'lucide-react';
import { supabase } from '../supabaseClient';
import type { User, PdfTextItem } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';
import * as pdfjsLib from 'pdfjs-dist';
import jsPDF from 'jspdf';
import Papa from 'papaparse';
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import DailyQuote from './DailyQuote';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

interface JournalEntry {
  id: string;
  title: string;
  content: string;
  date: Date;
  sentiment: 'positive' | 'neutral' | 'negative';
  tags: string[];
  wordCount: number;
}

interface JournalEntryRow {
  id: string;
  title: string;
  content: string;
  created_at: string;
  sentiment: JournalEntry['sentiment'];
  tags: string[] | null;
  word_count: number;
}

const JournalInterface = () => {
  const [currentEntry, setCurrentEntry] = useState('');
  const [currentTitle, setCurrentTitle] = useState('');
  const [journalEntries, setJournalEntries] = useState<JournalEntry[]>([]);
  const [user, setUser] = useState<User | null>(null);
  const [selectedEntry, setSelectedEntry] = useState<JournalEntry | null>(null);
  const { toast } = useToast();

  const writingPrompts = [
    "What am I most grateful for today?",
    "How did I show kindness to myself or others?",
    "What challenged me today and how did I respond?",
    "What emotions am I experiencing right now?",
    "What would I tell my younger self?",
    "What brought me joy or peace today?"
  ];

  const [currentPrompt, setCurrentPrompt] = useState(writingPrompts[0]);

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => {
      setUser(data.user);
      if (data.user) {
        supabase
          .from('journal_entries')
          .select('*')
          .eq('user_id', data.user.id)
          .order('created_at', { ascending: false })
          .limit(100)
          .then(({ data: rows, error }) => {
            if (error) {
              toast({ title: "Journal unavailable", description: "Your entries could not be loaded.", variant: "destructive" });
              return;
            }
            if (rows) {
              setJournalEntries(rows.map((row: JournalEntryRow) => ({
                id: row.id,
                title: row.title,
                content: row.content,
                date: new Date(row.created_at),
                sentiment: row.sentiment,
                tags: row.tags || [],
                wordCount: row.word_count
              })));
            }
          });
      }
    });
  }, [toast]);

  const handleSaveEntry = async () => {
    if (!currentEntry.trim()) return;
    if (!user) {
      toast({ title: "Sign in required", description: "Sign in before saving a journal entry.", variant: "destructive" });
      return;
    }

    try {
      // Simulate sentiment analysis
      const sentiment = currentEntry.toLowerCase().includes('happy') || currentEntry.toLowerCase().includes('grateful') || currentEntry.toLowerCase().includes('joy')
        ? 'positive'
        : currentEntry.toLowerCase().includes('sad') || currentEntry.toLowerCase().includes('angry') || currentEntry.toLowerCase().includes('frustrated')
        ? 'negative'
        : 'neutral';

      const newEntry: JournalEntry = {
        id: Date.now().toString(),
        title: currentTitle || `Entry from ${new Date().toLocaleDateString()}`,
        content: currentEntry,
        date: new Date(),
        sentiment,
        tags: [], // In a real app, this would be generated by AI
        wordCount: currentEntry.trim().split(/\s+/).length
      };

      const { error } = await supabase.from('journal_entries').insert({
        user_id: user.id,
        title: newEntry.title,
        content: newEntry.content,
        sentiment: newEntry.sentiment,
        tags: newEntry.tags,
        word_count: newEntry.wordCount,
        created_at: newEntry.date.toISOString()
      });

      if (error) throw error;

      setJournalEntries(prev => [newEntry, ...prev]);
      setCurrentEntry('');
      setCurrentTitle('');
      toast({ title: "Entry saved", description: "Your journal entry was added to your history." });
    } catch (err) {
      console.error("Failed to save journal entry:", err);
      toast({ title: "Entry not saved", description: "Please try again in a moment.", variant: "destructive" });
    }
  };

  // Add file import handlers
  const handleFileImport = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    event.target.value = '';
    if (!file) return;
    if (!user) {
      toast({ title: "Sign in required", description: "Sign in before importing journal entries.", variant: "destructive" });
      return;
    }
    if (file.size > 10 * 1024 * 1024) {
      toast({ title: "File too large", description: "Please upload a file under 10 MB.", variant: "destructive" });
      return;
    }
    if (file.type === 'text/csv') {
      Papa.parse(file, {
        complete: async (results) => {
          const text = (results.data as string[][]).map((row) => row.join(', ')).join('\n');
          const newEntry = {
            id: Date.now().toString(),
            title: 'Imported CSV Entry',
            content: text,
            date: new Date(),
            sentiment: 'neutral' as const,
            tags: [],
            wordCount: text.trim() ? text.trim().split(/\s+/).length : 0
          };
          if (!text.trim()) {
            toast({ title: "Empty file", description: "No journal text was found in that CSV.", variant: "destructive" });
            return;
          }
          const { error } = await supabase.from('journal_entries').insert({
            user_id: user.id,
            title: newEntry.title,
            content: newEntry.content,
            sentiment: newEntry.sentiment,
            tags: newEntry.tags,
            word_count: newEntry.wordCount,
            created_at: newEntry.date.toISOString()
          });
          if (error) {
            toast({ title: "Import not saved", description: error.message, variant: "destructive" });
            return;
          }
          setJournalEntries(prev => [newEntry, ...prev]);
          toast({ title: "CSV imported", description: "The imported entry was saved." });
        },
        error: () => toast({ title: "Import failed", description: "Failed to parse CSV file.", variant: "destructive" })
      });
    } else if (file.type === 'application/pdf') {
      const reader = new FileReader();
      reader.onload = async (e) => {
        try {
          const typedarray = new Uint8Array(e.target?.result as ArrayBuffer);
          const pdf = await pdfjsLib.getDocument({ data: typedarray }).promise;
          let text = '';
          for (let i = 1; i <= pdf.numPages; i++) {
            const page = await pdf.getPage(i);
            const content = await page.getTextContent();
            text += content.items.map((item) => (item as PdfTextItem).str).join(' ') + '\n';
          }
          if (!text.trim()) throw new Error('No readable text was found in this PDF.');
          const newEntry = {
            id: Date.now().toString(),
          title: 'Imported PDF Entry',
          content: text,
          date: new Date(),
          sentiment: 'neutral' as const,
          tags: [],
            wordCount: text.trim().split(/\s+/).length
          };
          const { error } = await supabase.from('journal_entries').insert({
          user_id: user.id,
          title: newEntry.title,
          content: newEntry.content,
          sentiment: newEntry.sentiment,
          tags: newEntry.tags,
          word_count: newEntry.wordCount,
          created_at: newEntry.date.toISOString()
          });
          if (error) throw error;
          setJournalEntries(prev => [newEntry, ...prev]);
          toast({ title: "PDF imported", description: "The imported entry was saved." });
        } catch (error) {
          toast({ title: "Import failed", description: error instanceof Error ? error.message : "The PDF could not be read.", variant: "destructive" });
        }
      };
      reader.onerror = () => toast({ title: "Import failed", description: "The PDF could not be read.", variant: "destructive" });
      reader.readAsArrayBuffer(file);
    } else {
      toast({ title: "Unsupported file", description: "Please upload a PDF or CSV file.", variant: "destructive" });
    }
  };

  const currentStreak = (() => {
    const days = new Set(journalEntries.map((entry) => entry.date.toISOString().slice(0, 10)));
    let streak = 0;
    const cursor = new Date();
    while (days.has(cursor.toISOString().slice(0, 10))) {
      streak += 1;
      cursor.setDate(cursor.getDate() - 1);
    }
    return streak;
  })();

  const handleDeleteEntry = async (entry: JournalEntry) => {
    if (!user || !window.confirm(`Delete “${entry.title}”? This cannot be undone.`)) return;
    const { error } = await supabase.from('journal_entries').delete().eq('id', entry.id).eq('user_id', user.id);
    if (error) {
      toast({ title: "Entry not deleted", description: error.message, variant: "destructive" });
      return;
    }
    setJournalEntries((entries) => entries.filter((item) => item.id !== entry.id));
    setSelectedEntry(null);
    toast({ title: "Entry deleted", description: "The journal entry was removed." });
  };

  // Export journal as CSV
  const exportJournalAsCSV = () => {
    const csvContent = Papa.unparse(journalEntries.map((entry) => ({
      Title: entry.title,
      Content: entry.content,
      Date: entry.date.toISOString(),
      Sentiment: entry.sentiment,
      Tags: entry.tags.join(';'),
      WordCount: entry.wordCount
    })));
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'journal_entries.csv';
    a.click();
    URL.revokeObjectURL(url);
  };

  // Export journal as PDF
  const exportJournalAsPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(12);
    let y = 15;
    journalEntries.forEach((entry) => {
      const contentLines = doc.splitTextToSize(entry.content, 185);
      const blockHeight = 30 + contentLines.length * 6;
      if (y + blockHeight > 285) {
        doc.addPage();
        y = 15;
      }
      doc.setFontSize(14);
      doc.text(entry.title, 10, y);
      doc.setFontSize(9);
      doc.text(`${entry.date.toLocaleString()} | ${entry.sentiment} | ${entry.wordCount} words`, 10, y + 7);
      doc.setFontSize(11);
      doc.text(contentLines, 10, y + 16);
      y += blockHeight;
    });
    doc.save('journal_entries.pdf');
  };

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment) {
      case 'positive': return 'bg-wellness-100 text-wellness-700 border-wellness-200';
      case 'negative': return 'bg-red-100 text-red-700 border-red-200';
      default: return 'bg-serenity-100 text-serenity-700 border-serenity-200';
    }
  };

  const getSentimentEmoji = (sentiment: string) => {
    switch (sentiment) {
      case 'positive': return '😊';
      case 'negative': return '😔';
      default: return '😐';
    }
  };

  return (
    <main className="min-h-screen bg-[#f5f3ef] pb-16 text-slate-900 dark:bg-slate-950 dark:text-white">
      <header className="border-b border-amber-950/10 bg-[#44382f] text-white">
        <div className="mx-auto grid max-w-7xl gap-6 px-4 py-9 sm:px-6 lg:grid-cols-[1fr_auto] lg:items-end lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-200">Private journal</p><h1 className="mt-3 font-serif text-4xl font-bold tracking-tight sm:text-5xl">A page for what is still unfolding.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65 sm:text-base">Write freely, return when you are ready, and let small reflections become a clearer story.</p></div><div className="grid grid-cols-3 gap-2 rounded-2xl bg-white/10 p-2"><div className="px-3 py-2 text-center"><p className="font-serif text-2xl font-bold">{journalEntries.length}</p><p className="text-[10px] uppercase text-white/50">entries</p></div><div className="px-3 py-2 text-center"><p className="font-serif text-2xl font-bold">{journalEntries.reduce((sum, entry) => sum + entry.wordCount, 0)}</p><p className="text-[10px] uppercase text-white/50">words</p></div><div className="px-3 py-2 text-center"><p className="font-serif text-2xl font-bold">{currentStreak}</p><p className="text-[10px] uppercase text-white/50">day streak</p></div></div></div>
      </header>
      <div className="mx-auto max-w-7xl px-3 py-6 sm:px-6 lg:px-8">
        <DailyQuote />
        <Tabs defaultValue="journal" className="w-full">
          <TabsList className="mx-auto mb-6 grid w-full max-w-md grid-cols-2 rounded-full bg-white p-1 shadow-sm dark:bg-slate-900">
            <TabsTrigger value="journal">Journal</TabsTrigger>
            <TabsTrigger value="forum">Forum</TabsTrigger>
          </TabsList>
          <TabsContent value="journal">
            {/* Export Buttons */}
            <div className="mb-3 flex flex-wrap justify-end gap-2">
              <Button variant="outline" className="rounded-full bg-white dark:bg-slate-900" size="sm" onClick={exportJournalAsCSV} disabled={!journalEntries.length}><Download className="mr-2 h-3.5 w-3.5" />CSV</Button>
              <Button variant="outline" className="rounded-full bg-white dark:bg-slate-900" size="sm" onClick={exportJournalAsPDF} disabled={!journalEntries.length}><Download className="mr-2 h-3.5 w-3.5" />PDF</Button>
            </div>
            <div className="grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(280px,.65fr)]">
              {/* Writing Area */}
              <div className="lg:col-span-2">
                <Card className="overflow-hidden rounded-[1.75rem] border-amber-900/10 bg-white shadow-xl shadow-amber-950/5 animate-fade-in dark:border-slate-800 dark:bg-slate-900">
                  <CardHeader>
                    <CardTitle className="flex items-center space-x-2">
                      <Feather className="w-5 h-5 text-amber-700 dark:text-amber-300" />
                      <span>New reflection</span>
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {/* AI Prompt */}
                    <div className="rounded-2xl border border-amber-100 bg-amber-50/70 p-4 dark:border-amber-900 dark:bg-amber-950/30">
                      <div className="flex items-center space-x-2 mb-2">
                        <Lightbulb className="w-4 h-4 text-calm-600" />
                        <span className="text-sm font-medium text-calm-700 dark:text-calm-200">Writing Prompt</span>
                      </div>
                      <p className="font-serif text-lg text-amber-950 dark:text-amber-100 italic mb-3">“{currentPrompt}”</p>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setCurrentPrompt(writingPrompts[Math.floor(Math.random() * writingPrompts.length)])}
                        className="rounded-full border-amber-200 text-amber-700 hover:bg-amber-100 dark:border-amber-800 dark:text-amber-200"
                      >
                        New Prompt
                      </Button>
                    </div>
                    {/* Title Input */}
                    <div>
                      <label className="text-sm font-medium text-gray-700 dark:text-gray-200 mb-2 block">Entry Title (Optional)</label>
                      <input
                        type="text"
                        value={currentTitle}
                        onChange={(e) => setCurrentTitle(e.target.value)}
                        maxLength={180}
                        placeholder="Give your entry a title..."
                        className="w-full border-0 border-b border-slate-200 bg-transparent px-1 py-3 font-serif text-xl outline-none focus:border-amber-500 dark:border-slate-700"
                      />
                    </div>
                    {/* Writing Area */}
                    <div>
                      <label className="text-sm font-medium text-gray-700 dark:text-gray-200 mb-2 block">Your Thoughts</label>
                      <Textarea
                        value={currentEntry}
                        onChange={(e) => setCurrentEntry(e.target.value)}
                        maxLength={10000}
                        placeholder="Start writing your thoughts here..."
                        className="min-h-80 resize-y rounded-2xl border-slate-200 bg-[#fdfcf9] p-5 text-base leading-7 dark:border-slate-700 dark:bg-slate-950"
                      />
                      <div className="mb-3 mt-2 flex items-center justify-between gap-3 text-sm text-gray-500 dark:text-gray-300">
                        <span>{currentEntry.split(' ').filter(word => word.length > 0).length} words</span>
                        <span>{Math.min(100, Math.round((currentEntry.split(' ').filter(word => word.length > 0).length / 250) * 100))}% of a 250-word reflection</span>
                      </div>
                      <div className="mb-4 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: `${Math.min(100, (currentEntry.split(' ').filter(word => word.length > 0).length / 250) * 100)}%` }} /></div>
                      <Button
                        onClick={handleSaveEntry}
                        disabled={!currentEntry.trim()}
                        className="rounded-full bg-amber-800 px-6 text-white hover:bg-amber-900"
                      >
                        Save Entry
                      </Button>
                      <label className="ml-2 inline-flex cursor-pointer items-center rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200">
                        <Upload className="mr-2 h-3.5 w-3.5" />Import
                        <input type="file" accept=".csv,application/pdf" onChange={handleFileImport} style={{ display: 'none' }} />
                      </label>
                    </div>
                  </CardContent>
                </Card>
              </div>
              {/* Journal History */}
              <div className="lg:col-span-1">
                <Card className="rounded-[1.75rem] border-slate-200 bg-white shadow-sm animate-fade-in dark:border-slate-800 dark:bg-slate-900" style={{animationDelay: '0.2s'}}>
                  <CardHeader>
                    <CardTitle className="flex items-center space-x-2">
                      <Calendar className="w-5 h-5 text-wellness-500" />
                      <span>Recent Entries</span>
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4 max-h-96 overflow-y-auto">
                      {journalEntries.length === 0 && (
                        <p className="py-8 text-center text-sm text-gray-500 dark:text-gray-400">No saved entries yet.</p>
                      )}
                      {journalEntries.map((entry) => (
                        <button type="button" key={entry.id} onClick={() => setSelectedEntry(entry)} className="w-full rounded-2xl border border-slate-200 p-4 text-left transition hover:-translate-y-0.5 hover:border-amber-300 hover:bg-amber-50/40 hover:shadow-sm dark:border-slate-700 dark:hover:bg-slate-800">
                          <div className="flex items-start justify-between mb-2">
                            <h3 className="font-medium text-gray-800 dark:text-white truncate">{entry.title}</h3>
                            <Badge className={`text-xs ${getSentimentColor(entry.sentiment)}`}>{getSentimentEmoji(entry.sentiment)}</Badge>
                          </div>
                          <p className="text-sm text-gray-600 dark:text-gray-300 line-clamp-3 mb-2">{entry.content}</p>
                          <div className="flex items-center justify-between text-xs text-gray-500 dark:text-gray-400">
                            <span>{entry.date.toLocaleDateString()}</span>
                            <span>{entry.wordCount} words</span>
                          </div>
                          <div className="flex flex-wrap gap-1 mt-2">
                            {entry.tags.map((tag) => (
                              <Badge key={tag} variant="secondary" className="text-xs">#{tag}</Badge>
                            ))}
                          </div>
                        </button>
                      ))}
                    </div>
                  </CardContent>
                </Card>
                {/* Writing Stats */}
                <Card className="mt-5 rounded-[1.75rem] border-slate-200 bg-[#44382f] text-white shadow-sm animate-fade-in dark:border-slate-800" style={{animationDelay: '0.4s'}}>
                  <CardHeader>
                    <CardTitle className="flex items-center space-x-2">
                      <Tag className="w-5 h-5 text-serenity-500" />
                      <span>Writing Stats</span>
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="text-center">
                        <div className="text-2xl font-bold text-wellness-600 mb-1">{journalEntries.length}</div>
                        <p className="text-xs text-white/55">Total Entries</p>
                      </div>
                      <div className="text-center">
                        <div className="text-2xl font-bold text-calm-600 mb-1">{journalEntries.reduce((sum, entry) => sum + entry.wordCount, 0)}</div>
                        <p className="text-xs text-white/55">Words Written</p>
                      </div>
                      <div className="text-center">
                        <div className="text-2xl font-bold text-serenity-600 mb-1">{journalEntries.filter(e => e.sentiment === 'positive').length}</div>
                        <p className="text-xs text-white/55">Positive Days</p>
                      </div>
                      <div className="text-center">
                        <div className="text-2xl font-bold text-wellness-600 mb-1">{currentStreak}</div>
                        <p className="text-xs text-white/55">Day Streak</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </TabsContent>
          <TabsContent value="forum">
            <div className="rounded-2xl border border-slate-200 bg-white px-6 py-16 text-center dark:border-slate-800 dark:bg-slate-900">
              <h2 className="font-serif text-2xl font-bold">Continue in Serenity Circle</h2>
              <p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600 dark:text-slate-300">The community forum opens as its own focused space, so your private journal and public discussions stay clearly separated.</p>
              <a href="/community" className="mt-6 inline-flex rounded-full bg-emerald-700 px-5 py-2.5 text-sm font-bold text-white hover:bg-emerald-800">Open community</a>
            </div>
          </TabsContent>
        </Tabs>
        <Dialog open={Boolean(selectedEntry)} onOpenChange={(open) => !open && setSelectedEntry(null)}>
          <DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto">
            {selectedEntry && (
              <>
                <DialogHeader>
                  <DialogTitle className="pr-8 font-serif text-2xl">{selectedEntry.title}</DialogTitle>
                  <DialogDescription>{selectedEntry.date.toLocaleString()} · {selectedEntry.wordCount} words · {selectedEntry.sentiment}</DialogDescription>
                </DialogHeader>
                <p className="whitespace-pre-wrap text-sm leading-7 text-slate-700 dark:text-slate-300">{selectedEntry.content}</p>
                <div className="flex justify-end border-t pt-4">
                  <Button variant="outline" className="border-rose-200 text-rose-600 hover:bg-rose-50 hover:text-rose-700" onClick={() => handleDeleteEntry(selectedEntry)}><Trash2 className="mr-2 h-4 w-4" />Delete entry</Button>
                </div>
              </>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </main>
  );
};

export default JournalInterface;
